### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Anydex** [Its-Vichy/Guilded-MassDm#4]
![image](https://user-images.githubusercontent.com/92234646/167275934-e956ce47-6571-46fb-903d-78559d34a8bf.png)
Gets stuck when logging into/checking accounts

**Comment by Its-Vichy** [comment]
I have logged into 1k and guilded was dead, they got shit server. Try with 5/10 account, they don't have anti-spam that can dm whole server ;)

**Comment by Anydex** [comment]
btw scraping is not working
